### ISSUE TITLE
Modal close buttons--hide font icon char from AT

### ISSUE THREAD

**Issue by weboverhauls** [dequelabs/pattern-library#11]
In the modal views, the font icon character for the close button is exposed to AT; need to hide to ensure AT doesn't output the character (as there's already alternative text provided).

```
<button class="dqpl-close" type="button">
  <div class="fa fa-close">::before</div>
  <div class="dqpl-offscreen">Close</div>
</button>
```
Recommend:
``` 
<div class="fa fa-close" aria-hidden="true">::before</div>
```

https://pattern-library.dequelabs.com/composites/modals

**Comment by schne324** [comment]
fixed by https://github.com/dequelabs/pattern-library/pull/12
