### ISSUE TITLE
Typo on wiki page for select component

### ISSUE THREAD

**Issue by isner** [dequelabs/pattern-library#14]
The section that describes how to set the [default selected option of a select component](https://github.com/dequelabs/pattern-library/wiki/selects#default-selected-option) uses an `id` of "yes" for the `aria-activedescendant` of the `role="combobox"` element and the `role="option"`, but has the wrong text content in the element with `class="dqpl-pseudo-val"`. This makes the example misleading.

Adjust the text content of the element with `class="dqpl-pseudo-val"` to "Yes". I'd do it myself, but these Wikis are under wraps.

**Comment by schne324** [comment]
Good catch, thanks @isner !
https://github.com/dequelabs/pattern-library/wiki/selects#default-selected-option
