### ISSUE TITLE
The select component repeatedly announces the selected option in VoiceOver with Safari

### ISSUE THREAD

**Issue by stowball** [dequelabs/pattern-library#22]
Selecting an option and then navigating through the options will repeatedly announce the selected one before the currently focused one

**Comment by schne324** [comment]
Thanks for logging this issue. I apologize for taking so long to get back to you on this.  I will be looking into fixing this within the next week or two.

**Comment by marcysutton** [comment]
I am finding this issue on the [axe playground](https://deque.com/axe/playground), which uses this component. From our QA team:

> "Dropdown options in the 'Rule' dropdown of ""select an example"" modal are not exposed to the screen reader users with VO in MAC - Safari. 

> Selected(Current dropdown option) option is exposed for all the dropdown option values when the user navigates to the options in the dropdown.
> Note: This issue is observed in 
> 1. MAC - safari"

**Comment by schne324** [comment]
This has been fixed in pattern-library@5.0.0 still haven't deployed to production but you can see the fix here: https://pattern-library-test.dequelabs.com/components/selects

I plan on deploying to production next week.
