### ISSUE TITLE
Utils folder missing in dist/js 

### ISSUE THREAD

**Issue by jducrot** [dequelabs/pattern-library#38]
dist/js/utils is referenced by pattern-library.js in the same folder but it's not included in the current download from npm (v 2.3.4).

**Comment by schne324** [comment]
`dist/js/pattern-library.js` is a bundled (via browserify) script.  At the moment, utils are used internally only and are not part of the distributed assets.  If you would find it useful for the utils to be included, please let me know your reasoning and we can look at adding them in for the next release.  

Is there any specific problem you're having? `dist/js/pattern-library.js` works by just dropping it in your page, for specific implementations please see the [wiki](https://github.com/dequelabs/pattern-library/wiki)

**Comment by jducrot** [comment]
When I tried using the downloaded library it returned an error saying "dist/js/utils could not be found". I can't remember if I was using the version in the `dist` folder now. I'll give it another shot.

**Comment by schne324** [comment]
I'm not sure what your setup is looking like but I quickly setup a codepen example usage of the pattern library: https://codepen.io/schne324/pen/KyqmLe

I've simply included `dist/js/pattern-library.js` and `dist/css/pattern-library.css` and stuff seems to be working fine with no exceptions thrown. (you can see the inclusion of those assets by clicking on the respective gear icons in the corner of the JS and CSS panels

I'm happy to help you out if you give me more info on your setup.
