### ISSUE TITLE
Component classes are unnecessarily prefixed

### ISSUE THREAD

**Issue by marcysutton** [dequelabs/pattern-library#42]
I'm updating our extensions to use a newer version of Cauldron and finding that there is extra CSS preventing a clean switchover. ~~Many~~ All of the classes are prefixed with `body .dqpl-layout`, which looks like it contains styles for the pattern library site (`top: 50px`). Those styles shouldn't be applied to things like `.dqpl-label`, or basic inputs.

For example, this CSS exists on the pattern library demo site, in `pattern-library.css`:

```
body .dqpl-layout .dqpl-label {
  display: block;
  text-align: left;
  font-size: 13px;
  font-weight: 300;
  margin-bottom: 4px;
  margin-left: 4px;
  cursor: default;
}
body .dqpl-layout .dqpl-label.dqpl-label-disabled {
  color: #cccccc;
}
body .dqpl-layout .dqpl-label.dqpl-required .dqpl-required-text {
  display: inline-block;
  margin-left: 24px;
  font-style: italic;
  font-weight: 400;
}
```

All of those things are in use in the Attest extension, but we can't use `dqpl-layout`. Is there a reason why those are prefixed in that way?

**Comment by schne324** [comment]
You bring up a very valid point. I think assuming that these components will ALWAYS be children of `.dqpl-layout` was an oversight.  Luckiily, it should be a quite easy fix to remove this over-qualification in css selectors

**Comment by marcysutton** [comment]
Awesome! We'll wait for a release to make the rest of the changes. Let me know if you need anything!

**Comment by WilcoFiers** [comment]
It's fairly urgent. We basically can't do an Attest release without it.

**Comment by schne324** [comment]
point to `deque-pattern-library@2.3.9`

**Comment by marcysutton** [comment]
Yay! Thanks guys! 
![dancing-banana](https://user-images.githubusercontent.com/1045233/34788358-3494c016-f5ef-11e7-89a9-cb9f127b955e.gif)
