### ISSUE TITLE
Use main-content:focus for other [tabindex=-1] elements

### ISSUE THREAD

**Issue by WilcoFiers** [dequelabs/pattern-library#46]
When the main content receives focus, instead of the purple focus ring, it has a bar on the left. This is actually much nicer, and it would be nice if this behaviour could be used on other elements as well. I think we need an option for that bar being inside or outside the focusable element.

**Comment by schne324** [comment]
this is up to @awpearlm and perhaps should be taken to a private discussion

**Comment by awpearlm** [comment]
Taken offline.
