### ISSUE TITLE
Please create a 2.4.4 release

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/pattern-library#57]
I'm still running into the issue from #55:

<img width="858" alt="yarn failed" src="https://user-images.githubusercontent.com/571265/38371594-d277671c-38ba-11e8-92fc-bf3a106ca656.png">

Can you please create a v2.4.4 release and publish it to npm?

**Comment by schne324** [comment]
done

**Comment by stephenmathieson** [comment]
Thanks dude!

**Comment by schne324** [comment]
no problem!
