### ISSUE TITLE
Review role for Selects Component

### ISSUE THREAD

**Issue by svinkle** [dequelabs/pattern-library#68]
I believe the [Selects Component](https://pattern-library.dequelabs.com/components/selects) might include an incorrect `role`. It currently features `role="combobox"`, and according to [ARIA Authoring Practices 1.1](https://www.w3.org/TR/wai-aria-practices-1.1/#combobox), a combobox is made up of a text `input` and a list of options, much like an [autocomplete component](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html).

When listening to the role descriptions, this component is announced as, "combo box," whereas a native `select` element is announced as "popup button" (VO + Safari at least.) 

When reviewing the "single select" [Collapsible Dropdown Listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html) demo, which features a `button` element and `aria-haspopup="listbox"`, this seems to accurately announce the role as one might expect.

Should this component's `role` be changed from `combobox` to `button` and include the `aria-haspopup="listbox"` attribute to ensure an accurate description? 🤔

**Comment by svinkle** [comment]
Now that I run my [test bed](https://codepen.io/svinkle/pen/mjgKBx) through both VO and NVDA, I see there's _some_ inconsistencies.

Screen reader | `role` | Announced as…
---|---|---
VO | native `select` | "popup button"
NVDA | native `select` | "combo box"
VO | `combobox` | "combo box"
NVDA | `combobox` | "combo box"
VO | `button` + `aria-haspopup="listbox"` | "popup button"
NVDA | `button` + `aria-haspopup="listbox"` | "button sub-menu"

These inconsistencies might make things a bit difficult… 😕

**Comment by yuheiy** [comment]
In ARIA in HTML, [the implicit role of select element is described as `combobox`](https://www.w3.org/TR/html-aria/#select).

**Comment by svinkle** [comment]
@yuheiy Good point. I still need to question this though:

1. VO native `select` is announced as "popup button" where and ARIA based widget would be "combo box"? This can't be a great user experience as a result. VO bug?
2. Is the markup for the [Collapsible Dropdown Listbox](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html) demo incorrect as a result of not featuring the `combobox` role?

**Comment by schne324** [comment]
Closing this because I don't see anything wrong with the implementation from a role standpoint...there's plenty wrong with it from an AT standpoint but that is covered in #22 and #21 

If you think I'm wrong, let me know and I will reopen this

**Comment by svinkle** [comment]
@schne324 No worries. I don't think there's any real solution here. It's too bad various AT announce native / ARIA roles differently. 😕

**Comment by schne324** [comment]
@svinkle agreed. The differences in announcements is rather large too...In my mind, theres a **HUGE** difference between`"combobox"` and `"popup button"`. Let's hope AT makes some improvements surrounding listboxes and comboboxes!
