### ISSUE TITLE
remove margin-left from `.dqpl-label`

### ISSUE THREAD

**Issue by schne324** [dequelabs/pattern-library#70]

**Comment by mariolo1985** [comment]
Hello - just stumbled upon this while doing my daily `Easy` label issue search 😄 but forgot to tack on `help-wanted` label in my search 🤣 my apologies for intruding.

It looks like line 80 on `lib/commons/forms.less` needs to be removed and it should be resolved.

**Comment by schne324** [comment]
@mariolo1985 you are absolutely correct, removing line 80 would resolve this issue. PR is welcomed if you're up for it 😄

**Comment by mariolo1985** [comment]
@schne324 thanks for allowing me to contribute 😃 

I created a PR for this here: https://github.com/dequelabs/pattern-library/pull/71

btw, I really like the toasts. It's a subtle attention grabber.
