### ISSUE TITLE
Use JS to get the value of a select / onChange events?

### ISSUE THREAD

**Issue by jcbreel** [dequelabs/pattern-library#83]
Is there currently a way to use JS to trigger an event when the value changes in a select?
I'm listening to 'blur' events but it triggers even when the value doesn't change.

**Comment by jcbreel** [comment]
Hey @schne324 , 
Yeah pretty much what I had in mind.
I'm not sure how to go about it though...

**Comment by jcbreel** [comment]
I'm currently using the 'blur' event and checking the selected value.
It's very erratic though and is not triggered at the right time when using the keyboard...

**Comment by schne324** [comment]
Yea using blur seems awkward. I will work on the above solution in the very near future but until then, unfortunately you may have to rely on a hacky solution. Heres a solution I came up with for the time being https://codepen.io/schne324/pen/XyRvMx

**Comment by schne324** [comment]
@jcbreel see the [updated pen](https://codepen.io/schne324/pen/XyRvMx?editors=1111) which supports multiple selects on the same page.  Keep in mind I'm using fancy newer stuff like arrow functions (`() => {}`) and `const` which means if you want to support older browsers you'll have to use normal functions (`function () {}`) and normal `var`s

**Comment by schne324** [comment]
#111 resolves this issue. Below is an example of how to use it (keep in mind we just updated the [select component in a non-backwards-compatible way](https://github.com/dequelabs/pattern-library/wiki/selects))

```js
// grab the select button
const select = document.querySelector('[aria-haspopup=listbox]');
select.addEventListener('dqpl:select:change', ({ detail }) => {
  console.log(`New value is ${detail.value}`)
});
```
