### ISSUE TITLE
axe reports violations for select component

### ISSUE THREAD

**Issue by mfairchild365** [dequelabs/pattern-library#97]
Reported violation: Certain ARIA roles must contain particular children (role="combobox" must contain a textbox)

URL: https://pattern-library.dequelabs.com/components/selects

**Comment by stephenmathieson** [comment]
@schne324 fyi

**Comment by schne324** [comment]
This has been fixed in pattern-library@5.0.0 still haven't deployed to production but you can see the fix here: https://pattern-library-test.dequelabs.com/components/selects
